name: Snippets Tests
description: Run Snippets Testss
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v1
      with:
        java-version: "11"
        architecture: x64
    - name: Build
      run: ./gradlew build shadowJar
      shell: bash
    - name: Launch Tests
      run: docker-compose -f .ci/doc/docker-compose.yml run doc-tests index
      shell: bash
