name: Snippets Tests
description: Run Snippets Testss
runs:
  using: "composite"
  steps:
    - name: Build
      run: ./gradlew thinJar fatJar
      shell: bash
    - name: Launch Tests
      run: docker-compose -f .ci/doc/docker-compose.yml run doc-tests index
      shell: bash
