name: Deploy package
description: Run Deploy package

inputs:
  MAVEN_CENTRAL_GPG:
    description: MAVEN_CENTRAL_GPG
    required: true
  MAVEN_CENTRAL_GPG_PASSWORD:
    description: MAVEN_CENTRAL_GPG_PASSWORD
    required: true
  OSSRH_PASSWORD:
    description: OSSRH_PASSWORD
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy to MavenCentral
      run: ./gradlew publish
      env:
        MAVEN_CENTRAL_GPG: ${{ inputs.MAVEN_CENTRAL_GPG }}
        MAVEN_CENTRAL_GPG_PASSWORD: ${{ inputs.MAVEN_CENTRAL_GPG_PASSWORD }}
        OSSRH_PASSWORD: ${{ inputs.OSSRH_PASSWORD }}
      shell: bash
