---
snippets:
  mount: /mnt
  path: 'doc/**/snippets/*.test.yml'
  templates: /mnt/.ci/doc/templates
  protocols:
    - http
    - websocket

runners:
  default: java

  java:
    debugStdout: false
    debugStderr: false
    service: doc-runner-java
    path: /var/snippets/java
    afterInit: /mnt/.ci/doc/snippet-build.sh
    run:
      cmd: SNIPPET_PROTOCOL="{{ snippet.protocol }}" /mnt/.ci/doc/test-snippet.sh "{{ snippet.source }}" "{{ snippet.name }}"
